services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
      args:
        MR_EXCEL_VERSION: V8.0.0
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  express-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.express
      args:
        MR_EXCEL_VERSION: V8.0.0
    ports:
      - "4000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  myapp:
    build:
      context: ./excel-validator
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "5000:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s