# Build Angular app
FROM node:24-alpine AS angular-builder
WORKDIR /app
ARG MR_EXCEL_VERSION=V8.0.0

COPY angular/package*.json ./


# install git first
RUN apk add --no-cache git

RUN echo "github:mohammadrezaeicode/mr-excel-repo#${MR_EXCEL_VERSION}"

RUN npm ci
RUN npm install "github:mohammadrezaeicode/mr-excel-repo#${MR_EXCEL_VERSION}"
# RUN npm install "github:mohammadrezaeicode/mr-excel-repo#${MR_EXCEL_VERSION}"

COPY angular/ .
RUN npm run build -- --base-href /app/

# Final Nginx image
FROM nginx:alpine

RUN apk add --no-cache curl

# Static website
COPY CDN/ /usr/share/nginx/html/static/

# Angular build output
COPY --from=angular-builder \
    /app/dist/angular/ \
    /usr/share/nginx/html/app/

# Nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf


# COPY --from=admin-builder /app/dist/ /usr/share/nginx/html/admin/
# COPY --from=dashboard-builder /app/dist/ /usr/share/nginx/html/dashboard/
# COPY static-site/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]